server:
  port: 8081
spring:
  h2:
    console:
      path: /h2
      enabled: true
      settings:
        web-allow-others: true
  application:    name: menu-service
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl : true  
    
eureka:  client:    service-url:      deafult-zone: http://localhost:8761